# Generated by Django 5.2.6 on 2025-09-10 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AUTH", "Authentication"),
                            ("USER", "User Management"),
                            ("COMPANY", "Company Management"),
                            ("BACKUP", "Backup & Restore"),
                            ("SECURITY", "Security"),
                            ("SYSTEM", "System"),
                            ("API", "API"),
                            ("DATABASE", "Database"),
                            ("FILE", "File Operations"),
                            ("OTHER", "Other"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True,
                        help_text="Request execution time in seconds",
                        null=True,
                    ),
                ),
                ("additional_data", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="core_system_timesta_7e67e4_idx"
                    ),
                    models.Index(fields=["level"], name="core_system_level_bf5286_idx"),
                    models.Index(
                        fields=["category"], name="core_system_categor_1fe2d6_idx"
                    ),
                    models.Index(
                        fields=["user"], name="core_system_user_id_6f81b7_idx"
                    ),
                ],
            },
        ),
    ]
