# Generated by Django 4.2.7 on 2025-09-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_project_workflowtemplate_workflowinstance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Employee profile photo",
                null=True,
                upload_to="employee_photos/",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail version of photo",
                null=True,
                upload_to="employee_photos/thumbnails/",
            ),
        ),
    ]
