# Generated by Django 4.2.7 on 2025-09-12 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_add_notification_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("manager_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_onboardings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_assignments",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Employment Contract"),
                            ("ID", "Government ID"),
                            ("TAX", "Tax Forms"),
                            ("BANK", "Banking Information"),
                            ("EMERGENCY", "Emergency Contact"),
                            ("MEDICAL", "Medical Information"),
                            ("POLICY", "Policy Acknowledgment"),
                            ("TRAINING", "Training Certificate"),
                            ("CUSTOM", "Custom Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                ("is_uploadable", models.BooleanField(default=True)),
                (
                    "file_types",
                    models.JSONField(
                        blank=True, default=list, help_text="Allowed file types"
                    ),
                ),
                ("max_file_size_mb", models.IntegerField(default=10)),
                (
                    "template_file",
                    models.FileField(blank=True, upload_to="onboarding_templates/"),
                ),
                ("template_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_documents",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="notification",
            name="is_global",
        ),
        migrations.CreateModel(
            name="OnboardingWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard Onboarding"),
                            ("EXECUTIVE", "Executive Onboarding"),
                            ("INTERN", "Intern Onboarding"),
                            ("CONTRACTOR", "Contractor Onboarding"),
                            ("REMOTE", "Remote Employee Onboarding"),
                            ("CUSTOM", "Custom Workflow"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("estimated_duration_days", models.IntegerField(default=7)),
                ("auto_assign", models.BooleanField(default=True)),
                ("target_departments", models.JSONField(blank=True, default=list)),
                ("target_positions", models.JSONField(blank=True, default=list)),
                ("target_employment_types", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_workflows",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document Collection"),
                            ("TRAINING", "Training Module"),
                            ("MEETING", "Meeting/Session"),
                            ("FORM", "Form Completion"),
                            ("EQUIPMENT", "Equipment Setup"),
                            ("ACCOUNT", "Account Setup"),
                            ("POLICY", "Policy Review"),
                            ("COMPLIANCE", "Compliance Check"),
                            ("CUSTOM", "Custom Task"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("estimated_duration_minutes", models.IntegerField(default=30)),
                ("is_required", models.BooleanField(default=True)),
                ("is_sequential", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "auto_assign_to",
                    models.CharField(
                        blank=True,
                        help_text="Role or department to auto-assign to",
                        max_length=50,
                    ),
                ),
                (
                    "assignee_type",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("MANAGER", "Manager"),
                            ("HR", "HR Team"),
                            ("IT", "IT Team"),
                            ("ADMIN", "Administrator"),
                        ],
                        default="EMPLOYEE",
                        max_length=20,
                    ),
                ),
                (
                    "resources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Links, documents, or resources",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True, default=list, help_text="File attachments"
                    ),
                ),
                ("completion_criteria", models.TextField(blank=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approval_role", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependent_tasks",
                        to="core.onboardingtask",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_tasks",
                        to="core.onboardingworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingDocumentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(blank=True, upload_to="onboarding_documents/"),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RESUBMITTED", "Resubmitted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("resubmitted_at", models.DateTimeField(blank=True, null=True)),
                ("resubmission_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="core.onboardingdocument",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_submissions",
                        to="core.employee",
                    ),
                ),
                (
                    "onboarding_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_submissions",
                        to="core.onboardingassignment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="onboardingdocument",
            name="workflows",
            field=models.ManyToManyField(
                blank=True,
                related_name="required_documents",
                to="core.onboardingworkflow",
            ),
        ),
        migrations.AddField(
            model_name="onboardingassignment",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_assignments",
                to="core.onboardingworkflow",
            ),
        ),
        migrations.CreateModel(
            name="OnboardingTaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("completion_notes", models.TextField(blank=True)),
                ("completion_attachments", models.JSONField(blank=True, default=list)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "onboarding_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="core.onboardingassignment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="core.onboardingtask",
                    ),
                ),
            ],
            options={
                "ordering": ["task__order", "assigned_at"],
                "unique_together": {("onboarding_assignment", "task")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="onboardingassignment",
            unique_together={("employee", "workflow")},
        ),
    ]
