# Generated by Django 4.2.7 on 2025-09-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_document_management_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="announcement_type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("BILLING", "Billing"),
                    ("SYSTEM", "System"),
                    ("CHAT", "Chat"),
                    ("FILE", "File"),
                    ("LEAVE", "Leave"),
                    ("BENEFIT", "Benefit"),
                    ("CUSTOMER", "Customer"),
                    ("CONTACT", "Contact"),
                    ("MAINTENANCE", "Maintenance"),
                    ("INVENTORY", "Inventory"),
                    ("DATA_PROTECTION", "Data Protection"),
                    ("SECURITY", "Security"),
                    ("WEBHOOK", "Webhook"),
                    ("EXPORT", "Export"),
                    ("INSIGHT", "Insight"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
