# Generated by Django 4.2.7 on 2025-09-12 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_announcement_announcement_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "Credit Card"),
                            ("DEBIT_CARD", "Debit Card"),
                            ("BANK_ACCOUNT", "Bank Account"),
                            ("PAYPAL", "PayPal"),
                            ("STRIPE", "Stripe"),
                        ],
                        default="CREDIT_CARD",
                        max_length=20,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VISA", "Visa"),
                            ("MASTERCARD", "Mastercard"),
                            ("AMERICAN_EXPRESS", "American Express"),
                            ("DISCOVER", "Discover"),
                            ("JCB", "JCB"),
                            ("DINERS_CLUB", "Diners Club"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_four_digits", models.CharField(max_length=4)),
                ("expiry_month", models.CharField(blank=True, max_length=2, null=True)),
                ("expiry_year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "cardholder_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
                "unique_together": {
                    ("company", "last_four_digits", "expiry_month", "expiry_year")
                },
            },
        ),
    ]
