# Generated by Django 5.2.6 on 2025-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_premium",
            field=models.BooleanField(
                default=False, help_text="Whether company has premium features"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="license_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When the license expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="license_key",
            field=models.CharField(
                blank=True,
                help_text="License key for premium features",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("STARTER", "Starter"),
                    ("PROFESSIONAL", "Professional"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="FREE",
                max_length=20,
            ),
        ),
    ]
